### ISSUE TITLE
Berry Flavors

### ISSUE THREAD

**Issue by zaneadix** [veekun/pokedex#158]
I can't help but feel that the Berry Flavor table is tied pretty awkwardly to Contest Types. It seems like it would be a better fit to have Berry Flavor, Berry Flavor Names and use a mapping table between Berries and Berry Flavors. Berry Flavors could also hold foreign key references to Contest Types. Then the 'flavor' attribute could be removed from the Contest Type Name table. 

For example:

berry_flavors.csv
```
id, identifier, contest_type
1, spicy, 1
2, dry, 2
3, bitter, 3
4, sweet, 4
5, sour, 5
```
---
berry_flavor_names.csv
```
berry_flavor_id,local_language_id,name
1, 9, Spicy
2, 9, Dry
3, 9, Bitter,
4, 9, Sweet
5, 9, Sour
```
---
berry_flavor_map.csv
```
berry_id, berry_flavor_id, potency
1, 1, 10
1, 2, 0
1, 3, 0
1, 4, 0
1, 5, 0
...
```
---
Does this make sense? I think it would fit the same logical separation of most other resources across tables.

**Comment by magical** [comment]
Contest types and berry flavors are tied together because... well, they *are* tied together. They're pretty much synonymous. What would be the advantage of separating them?

**Comment by zaneadix** [comment]
I guess no real technical advantage. The idea mostly just came from how the rest of the relations work in terms of how we're serving the data on pokeapi so I thought I would mention it. If theres no real advantage to this project specifically then this issue can just be closed. I wont pout :)
