### ISSUE TITLE
Flavour text formatting? [Question]

### ISSUE THREAD

**Issue by FarbodSalamat-Zadeh** [veekun/pokedex#164]
This is more a question than an issue, but I was looking at the [`pokemon_species_flavor_text.csv`](https://raw.githubusercontent.com/veekun/pokedex/master/pokedex/data/csv/pokemon_species_flavor_text.csv) file, and it seems like descriptions are separated to multiple lines for some reason.

For example:
```
1,1,9,"A strange seed was
planted on its
back at birth.The plant sprouts
and grows with
this POKéMON."
```

Why is there a gap/newline between _was_ and _planted_, _its_ and _back_, etc. - is there a particular reason for this?

**Comment by DrDos0016** [comment]
I believe this just matches the line breaks used in the games themselves.

**Comment by FarbodSalamat-Zadeh** [comment]
@DrDos0016 Thanks for the quick reply.

Is there the line breaks can be removed?
Alternatively, when _veekun_ reads this file, how does it concatenate the descriptions from different lines?

**Comment by xfix** [comment]
Veekun uses \n to mark next line, and \f to mark a page. If you want to remove it for display purpoess, replace \n and \f with a space.

If you mean parsing this, use a proper CSV parser, don't parse it manually. Veekun itself uses SQL, CSV is just a storage for data that is going to be uploaded into a database using PostgreSQL's COPY command.
