### ISSUE TITLE
Mega Name Language

### ISSUE THREAD

**Issue by miguelsotobaez** [veekun/pokedex#168]
Hello , first of all I want to thank you for compiling this excellent information .
Now I have a question and I would like you to help me solve .

Question:
How I can reference the name of the pokemon when they are MEGA ?
I tried to cross the table pokemon with pokemon_species_name , but the name of the Mega Pokemon was not translated, such as " Mega Charizard X", they say 3 times "Charizard"

That's my question , Greetings.

**Comment by miguelsotobaez** [comment]
OK, i think i have to cross with table pokemon_forms first.

Thanks anyway.

**Comment by magical** [comment]
Yes, mega form names are in pokemon_form_names, which references pokemon_forms, which references pokemon, which references pokemon_species. It's all a bit confusing. Glad you were able to figure it out.
