### ISSUE TITLE
Stat Calculator doesn't take maximum IV according to characteristic into account

### ISSUE THREAD

**Issue by bladeoflight16** [veekun/pokedex#171]
[Here](http://veekun.com/dex/gadgets/stat_calculator?stat=28%2C17%2C23%2C11%2C13%2C15&stat=37%2C24%2C32%2C16%2C17%2C20&level=10&level=15&effort=0%2C0%2C0%2C0%2C0%2C0&effort=0%2C0%2C0%2C0%2C0%2C0&hint=26&hp_type=11&pokemon=Nincada&nature=adamant) is an example.

Notice three things:

 1. The characteristic is Quick Tempered. This means that all IVs are less than or equal to the Attack IV. (See [Bulbapedia](http://bulbapedia.bulbagarden.net/wiki/Characteristic).)
 1. The stat calculator has determined that the Special Attack IV is 28.
 1. The stat calculator can't determine whether the Attack IV is 24 or 29.

However, since the characteristic tells us that all IVs mus be less than or equal to the Attack IV, the Attack IV cannot be 24 since this would be lower than the Special Attack IV.

It would be helpful if the stat calculator took this into account and eliminated 24 for the possible IVs automatically. In combination with the Hidden Power calculation, this might narrow down some other IVs as well.

Thanks for the Pokedex and tools!

**Comment by magical** [comment]
Interesting. The stat calculator is already capable of using the maximum value of the Attack stat gene (in this case) to eliminate larger genes in other stats, but not the other way around.

**Comment by magical** [comment]
Er, scratch that. It should be doing what you suggest as well https://github.com/veekun/spline-pokedex/blob/master/splinext/pokedex/controllers/pokedex_gadgets.py#L1036. Must be a bug somewhere.

**Comment by bladeoflight16** [comment]
Off-hand, I'm wondering if maybe `filter_genes` isn't updating `valid_genes` properly. There's a `genes &=` inside `filer_genes`, but isn't that just reassigning the local variable?

**Comment by magical** [comment]
If filter_genes was a no-op then the stat calculator would be a lot more broken than it is. Augmented assignment operators like `&=` can modify a collection in-place in python.

**Comment by bladeoflight16** [comment]
I don't think this line finds the number we actually want:
```
min_gene = min(itertools.chain(genes, (999,)))
```
That finds the absolute minimum of the entire stat set, right? So in the example data, it should give back `0`. But the minimum of everything isn't what we want. We want to *biggest* minimum (28 in the example). So it should be something more like this:
```
min_gene = max(min(g) for g in genes)
```
That needs to be modified to handle whatever case the `(999,)` was before, but it's not clear to me what case that was or how to do it. I don't have time right now, but I might could take a look later.

**Comment by eevee** [comment]
I, uh, seem to have just not done a deploy since that code was added.  It works correctly locally.
