### ISSUE TITLE
Paths for Windows are not Updated

### ISSUE THREAD

**Issue by Alpiral** [veekun/pokedex#182]
Hi,
Some paths in the documentation are not available. For example there is no C:\Python\Python27 folder. It is just C:\Python27.
Also there is no bin folder anymore. Can someone update the guideline? Thanks.

**Comment by magical** [comment]
Thanks. I've updated the wiki page: https://github.com/veekun/pokedex/wiki/Getting-Data. Let me know if there are still issues.
