### ISSUE TITLE
[Question] Is this project still maintained?

### ISSUE THREAD

**Issue by metaunicorn** [veekun/pokedex#209]
I was wondering if this project is still maintained or not, or is going to be discontinued or going to stop being supported?

Why am I asking this?
- No updates since last year (latest master commit is from more than 6 months ago)
- A lot of stale branches (well, all of them).
- Issues not being answered by the owner and/or "official" project maintainers.
- Pull Requests not being answered / merged. Some of them from years ago.
- No apparent interest about bringing Gen 7 data

**Comment by eevee** [comment]
It is, just, very slowly.  Only a couple people are still working on it, and we all have a lot of other stuff going on.  Whenever I dedicate time to it I focus on gen 7, since that's the most immediately important, so anything else is on hold and there won't appear to be much progress until gen 7 is done.

**Comment by metaunicorn** [comment]
Ok thanks for the quick answer @eevee , how do you plan to import the Gen 7 data, manually?
I am currently putting some effort there, [trying to import the existing Showdown data](https://github.com/metaunicorn/veekun-pokedex-migrations).
Or do you have a better way/tool in mind to automate it, at least to have initial basic data?

**Comment by eevee** [comment]
Automatically and directly from the ROM.  Everything we have at the moment was ripped by a lot of one-off scripts that are scattered all over the place and mostly lost.  I've been working on writing something that's 100% repeatable and requires no manual intervention.  It should make future games much faster to dump, but it's proving to be a bit of a slog to finish.

**Comment by metaunicorn** [comment]
Oh cool, good to know ;)

**Comment by tills13** [comment]
I hate to ask this because I hate when I'm asked this, but is there an ETA for gen 7?

**Comment by eevee** [comment]
The last four ETAs I gave were many months ago now, so, no  :)

**Comment by metaunicorn** [comment]
@eevee Do you need help? I would like to contribute but I don't know what tools you use for data mining the ROMs, any recommendation / suggestion?
I would like to know what's necessary in order to get the data from the games.

**Comment by endrift** [comment]
Most of the data is in numbered GARC files that you need to dump from the romfs. You can obtain the romfs using something like braindump or get the whole image using Decrypt9. Then IIRC ctrtool will let you grab the romfs from the .3ds (the output of Decrypt9), and I think it can also extract the romfs. The GARC files have been indexed on some sites already, although I don't know where offhand. If you search for "Pokemon Sun Moon GARC index" you might be able to find some info or tools.

**Comment by eevee** [comment]
The work I've been doing so far is on the `yaml` branch, if you want to take a look.  It's definitely a bit, uh, fiddly.

**Comment by metaunicorn** [comment]
Thanks for the suggestions, @endrift 
I will try to get familiar with the code and the GARC world, so I may be able to contribute @eevee 

Closing this thread.

**Comment by eevee** [comment]
So I just realized that my current YAML-dumping code relies on local changes to [camel](https://github.com/eevee/camel) that don't exist anywhere but on my computer?  Whoops.  I should probably fix that.

On the other hand, I've directed several people to that branch before and no one's ever noticed...  hmm.  :)

**Comment by metaunicorn** [comment]
I noticed that today, I didn't find t hem so I was trying to guess how were you generating them from the code LOL
