### ISSUE TITLE
Data Modeling

### ISSUE THREAD

**Issue by GCSBOSS** [veekun/pokedex#211]
Hello!

I have been working on a JSON API hugely based on this project (at least its raw csv files), but I am having trouble on understanding many tables and their connections. Would we have any priority for making diagrams and data modeling (ER, Classes (UML)) or anything alike in the near future? I would also voluntary if I can get help from someone with knowledge about this data,

Thanks for your time!

**Comment by magical** [comment]
Hi,

Good luck on your project. There is some documentation at https://veekun.github.io/pokedex/main-tables.html which might be helpful. I don't know of any diagram of the schema. I assume ER refers to entity-relationship model; I'm not sure what you mean by Classes. Either way, it's not a high priority right now (the only person actively working on the pokedex right now is eevee, who is working on getting Sun/Moon data imported). If you want to contribute something along those lines, you are more than welcome to.

The best way to get help with the pokedex would probably be to ask questions in the IRC channel; see https://veekun.com/chat.

**Comment by GCSBOSS** [comment]
Thanks for the docs. Well, I shall come up with these models anyway for my project, I might PR with them once they are ready.

I will visit the chat, thanks again!
