### ISSUE TITLE
Totem Salazzle's English name is listed as Salazzle Lurantis

### ISSUE THREAD

**Issue by jpirnat** [veekun/pokedex#216]
https://github.com/veekun/pokedex/blob/master/pokedex/data/csv/pokemon_form_names.csv
https://veekun.com/dex/pokemon/salazzle?form=totem

Accidental copypaste?

**Comment by magical** [comment]
Thanks. Fixed in https://github.com/veekun/pokedex/commit/82679b70ead372d27fb52e2a7e3328de46b38865
