### ISSUE TITLE
[Feature Request] Ultra Sun / Moon data

### ISSUE THREAD

**Issue by itsjavi** [veekun/pokedex#220]
Hello I know It is maybe a bit early for this, but since the USUM data mining seems to be more or less over, It would be nice to start importing it to the project.
Thanks!

**Comment by magical** [comment]
Good news, everyone! Eevee added Ultra Sun/Moon data a few days ago: https://github.com/veekun/pokedex/commit/45f43231e32d17f8997a823e838d27ad191b3915.

Let us know if something is still missing.
