### ISSUE TITLE
No pokemon evolution relational table.

### ISSUE THREAD

**Issue by ahester57** [veekun/pokedex#227]
In pokemon_evolutions, the id column does not match up with the species_id. And there is no pokemon_id column to filter with. Also evolution_chains only has id & baby_item_id. How are we supposed to find the evolutions?

**Comment by magical** [comment]
You're looking for pokemon_species.evolves_from_species_id.  The pokemon_evolution tables only tells you how a pokemon evolves, not what it evolves from. I agree that this is a little weird.

**Comment by ahester57** [comment]
Yea it is weird. I have the evolves from working, but evolves to using the same method gives me something wrong. e.g. Aipom evolves from None but evolves to metang. So I have to filter species with evolves_from_species_id.
