### ISSUE TITLE
Location Data for Gen VII missing

### ISSUE THREAD

**Issue by ahester57** [veekun/pokedex#230]
Locations in Alola are missing. Therefore the Pokemon which evolve in a certain location (such as vikavolt and crabominable) do not have any evolution information available. When adding Alolan locations, do not forget to add location_id to the Gen 7 PokemonEvolution table.

**Comment by ahester57** [comment]
https://github.com/ahester57/pypoke This is my CLI wrapper for y'all's pokedb, written in Python. It's quite simple, still working on it though.

**Comment by metaunicorn** [comment]
I would consider importing all missing data from the PKHex project...
