### ISSUE TITLE
Why are Pokemon weight and height from the API 10x their actual value?

### ISSUE THREAD

**Issue by arnavb** [veekun/pokedex#249]
So when I was using [PokeAPI](https://pokeapi.co/), I found that running a `GET` request on a Pokemon yields heights and weights for Pokemon that are 10x their original value. In order to find out the reasoning behind this, I [opened an issue](https://github.com/PokeAPI/pokeapi/issues/380) on PokeAPI. The response there was that "[w]e take our data from Veekun [and] [w]e do not modify" it.

So I will ask the same question here: _Why are Pokemon weight and height from the API 10x their actual value?_

**Comment by encukou** [comment]
It's an issue of units: The games store height in *decimeters* and weight in *decagrams* (good units to use if you need to store the info as whole numbers, but extremely weird for any other use, like displaying the data to people).

See: https://github.com/veekun/pokedex/blob/master/pokedex/db/tables.py#L1649

**Comment by arnavb** [comment]
So just to clarify, these values are just going to be kept as is?

**Comment by encukou** [comment]
I don't have much say here any more, but I think I can answer this :)

Yes, they will be kept as whole numbers, as the games store them.
Integers are a better fit than floats (which are inexact) or decimals (which are not as readily available in most programming languages).

**Comment by arnavb** [comment]
Cool, thanks for the clarification!
