### ISSUE TITLE
Generation VII's name doesn't follow standard of other Generation names

### ISSUE THREAD

**Issue by SethETaron** [veekun/pokedex#251]
Generation VII's name is "sun-moon", but all other generation names are named like "generation-i", "generation-ii", etc. It should be changed to conform to this standard.

**Comment by magical** [comment]
Oh weird, you're right. @eevee, was this intentional?

**Comment by SethETaron** [comment]
If it turns out to not be intentional, I created an MR with modifications for this issue and also 250 and 252 :)

**Comment by eevee** [comment]
I have no idea why I did this!  Probably hit up-enter a little too eagerly after adding the version group.

**Comment by SethETaron** [comment]
Makes perfect sense! I added the change in PR #253 :)
