### ISSUE TITLE
Multiple rows returned with uselist=False for eagerly-loaded attribute 'PokemonMove.machine

### ISSUE THREAD

**Issue by magical** [veekun/pokedex#261]
Happens in one of the spline-pokedex tests. Haven't investigated what's triggering it.

> `lib/python2.7/site-packages/sqlalchemy/orm/loading.py:305: SAWarning: Multiple rows returned with uselist=False for eagerly-loaded attribute 'PokemonMove.machine`

**Comment by magical** [comment]
This seems to be because Waterfall, Surf, and Fly are both HMs and TMs in S/M and US/UM. I'm not sure why we even have HMs for those games -- i guess they're in the data, but unused?

**Comment by Parnassius** [comment]
This should be now fixed (80bc35a764295a86dc09d49672265d9f8b7ce3a2)
