### ISSUE TITLE
Corrupted data

### ISSUE THREAD

**Issue by ticowiko** [veekun/pokedex#263]
The following machines are incorrectly associated with HMs :

`1195, 1209, 1190, 1212, 1203, 1206, 1200, 1215`

What they are in fact is TMs 93 to 100 for ORAS.

**Comment by magical** [comment]
The ids you listed don't seem to correspond to anything in [machines.csv](https://github.com/veekun/pokedex/blob/master/pokedex/data/csv/machines.csv). In any case, i think the problem you're talking about was fixed by #206.
