### ISSUE TITLE
Missing sprites for No. 802 ~ 807

### ISSUE THREAD

**Issue by ymin1103** [veekun/pokedex#268]
I can't find sprites for following pokemon.

- No 802. Poipole
- No 803. Naganadel
- No 804. Stakataka
- No 805. Blacephalon
- No 806. Zeraora

**Comment by magical** [comment]
These are present on the site and in pokedex-media.

https://veekun.com/dex/media/pokemon/main-sprites/ultra-sun-ultra-moon/807.png

**Comment by azzamsa** [comment]
The git repo for pokedex-media is down https://git.veekun.com/pokedex-media.git. Anyone know the new link?

**Comment by magical** [comment]
@azzamsa It's still there, just not over https. http://git.veekun.com/pokedex-media.git. (Also please don't respond to an unrelated closed issue. Open a new issue if you have to.)
