### ISSUE TITLE
contest_effect_id 22 is mapping to 21

### ISSUE THREAD

**Issue by whiterkim** [veekun/pokedex#280]
Some `contest_effect_id` in moves.csv are not correct.
It is very likely the `contest_effect_id` 22 is mapping to 21.
I did not checking all `contest_effect_id` 22 moves, but there is no 22 move in the list. And the two examples below are the moves that should have `contest_effect_id` 22 but showing 21.

For example:
    247,shadow-ball,2,8,80,15,100,0,10,3,73,20,4,**21**,17
    https://bulbapedia.bulbagarden.net/wiki/Shadow_Ball_(move)
    352,water-pulse,3,11,60,20,100,0,10,3,77,20,2,**21**,17
    https://bulbapedia.bulbagarden.net/wiki/Water_Pulse_(move)

**Comment by magical** [comment]
You're right. Looks like it's been that way since the first commit. We should probably do a re-rip.
