### ISSUE TITLE
Support for Sword and Shield?

### ISSUE THREAD

**Issue by mirekdlugosz** [veekun/pokedex#281]
Pokemon Sword and Shield are going to be released within two months. @eevee last committed almost two years ago, and there were only handful of contributions since then.

Are Sword and Shield on a roadmap? Any timeline when that data might be available?

**Comment by eevee** [comment]
Project activity aside, I have _absolutely no idea_ what the state of Switch hacking is or what the internals of a Switch game image look like.  Sorry, but I think someone else will have to lead the charge for this one.

**Comment by mirekdlugosz** [comment]
Thanks for your answer!
