### ISSUE TITLE
Getting Data Wiki Page insists on Python 2

### ISSUE THREAD

**Issue by kupiakos** [veekun/pokedex#285]
The [Getting Data](https://github.com/veekun/pokedex/wiki/Getting-Data) Wiki page is insistent that Python 2 must be used. However, based on the code, that's not required anymore. Should it be updated?

**Comment by magical** [comment]
Probably. We definitely support Python 3 now. Looks like that warning was added in 2012.

**Comment by route1rodent** [comment]
I edited the wiki page and I am preparing a PR to fix setup on python 3.7

**Comment by magical** [comment]
I've edited the wiki page to remove the warning.
