### ISSUE TITLE
"Ground" egg group has not been converted to "Field"

### ISSUE THREAD

**Issue by clarkanine** [veekun/pokedex#293]
egg_groups.csv lists "ground" as an egg group. Since Diamond and Pearl, it is now "Field".

**Comment by magical** [comment]
`ground` is just the identifier. The name is in `egg_group_prose.csv` and it has already been changed to Field.

https://github.com/veekun/pokedex/blob/7d5fbae/pokedex/data/csv/egg_group_prose.csv#L36

**Comment by clarkanine** [comment]
Gotcha will close. Thanks for informing.
