### ISSUE TITLE
flavor_text_entries (description) hasn't a fix index for each language

### ISSUE THREAD

**Issue by Nicoji** [veekun/pokedex#305]
Hi, 
I'm having a lot of fun learning Javascript using Pokéapi, so first thank you for that ! 
I've created a pokedex (in french), and i'm using [flavor_text_entries] to get the pokemon's description. So in https://pokeapi.co/api/v2/pokemon-species/1 I'm getting `[flavor_text_entries][5][flavor_text]` to have the french description of the pokemon. In this case (for bulbasaur) I indeed have the french description. But for Starmie for example (id 121), `[flavor_text_entries][5][flavor_text]` return the description in German. 
So I've tested on several pokemon, and it happens that some have a french description and some have a german one. I can I fix that to always have the french one ? Cheers !

**Comment by magical** [comment]
It sounds like you're describing an issue with PokeAPI, not with veekun. Please try PokeAPI's issue tracker: https://github.com/PokeAPI/pokeapi/issues/.
