### ISSUE TITLE
Duplicate Spanish characteristic text

### ISSUE THREAD

**Issue by venustoise** [veekun/pokedex#309]
In characteristic_text.csv
Hi, I've noted that characteristic#14 Spanish text is erroneously the same as characteristic#26 (correct).
According to https://bulbapedia.bulbagarden.net/wiki/Characteristic :
- Characteristic#14 (A little quick tempered) in Spanish is "A veces se enfada", not "Tiene mal genio";
instead characteristic#26 is correct, English=>"Quick tempered" (so similar!), Spanish=>"Tiene mal genio".
Bye!

**Comment by magical** [comment]
How embarrassing! Thanks for the report.
