### ISSUE TITLE
Invisible char

### ISSUE THREAD

**Issue by Naramsim** [veekun/pokedex#321]
Hello, I just discovered that there is an invisible character every second line in the file _pokemon_species_flavor_text_ for each ability. It's always in between the columns ranging from 14 to 20.

The character is "". Yes, it's in between the quotes. Here the ASCII representation:

|Char|Dec|Hex|Oct|
|---|---|---|---|
| |12|0C|14|

To find it you can just move the cursor from the beginning of the line to the end. An example is line 4.

Is it normal? Would you consider removing it? I can submit a PR is so.

**Comment by coreyog** [comment]
Potential duplicate of https://github.com/veekun/pokedex/issues/218

**Comment by magical** [comment]
That's a form feed character. Its purpose is to mark the break between pages in the dex entries in the first couple generations of games.

There's some previous discussion on https://github.com/veekun/pokedex/issues/218#issuecomment-339841781

**Comment by Naramsim** [comment]
Great, thanks for the quick reply! So it's actually a known and wanted behavior. Closing 😄
