### ISSUE TITLE
move_effects.csv missing data

### ISSUE THREAD

**Issue by zyugyzarc** [veekun/pokedex#350]
i am using this repo's csv files to use in my code (code is in python, but im using the raw csv files from data/csv/*.csv)
move_effects.csv seems to not have enough information/data thats supposed to be there.
upon previewing the file, it seems to only have one column - "id" and nothing else.
i think this might be an effect of the csv to yaml conversion or something but i dont know.

**Comment by zyugyzarc** [comment]
for convinience, here is the url to the file: [https://github.com/veekun/pokedex/blob/master/pokedex/data/csv/move_effects.csv](https://github.com/veekun/pokedex/blob/master/pokedex/data/csv/move_effects.csv)

**Comment by meowsticdf** [comment]
That's an intentional consequence of how localised text is implemented. The `move_effect_prose.csv` file contains the information about move effects, so you can use that and ignore `move_effects.csv`.

**Comment by zyugyzarc** [comment]
thanks, will use `move_effects_prose.csv`

suggession, `move_effects.csv` could contain psuedo code so its easier to implement into other stuff
for example, the move "tail whip" can be described as `target[defense -20%]`
if you feel that this is a lot of work, i am willing to help towards this

**Comment by magical** [comment]
> for example, the move "tail whip" can be described as `target[defense -20%]`

There is already some data like that in the move_meta tables; in particular, [move_meta_stat_changes](https://github.com/veekun/pokedex/blob/master/pokedex/data/csv/move_meta_stat_changes.csv) and move_target.

See the [table documentation](http://veekun.github.io/pokedex/main-tables.html) for more info.
