### ISSUE TITLE
Acquire Dream World artwork

### ISSUE THREAD

**Issue by encukou** [veekun/pokedex#43]
**Reported by [Eevee](http://github.com/eevee) on 2011/04/22 04:45:58 +0000 · Migrated from [Redmine issue 584](http://bugs.veekun.com/issues/584)**

---

Pokémon, items.

I think there are two images for each Pokémon; one used as stock art, and one used within the Dream World itself. Zhorken was looking into this and each of the latter is actually just its own Flash file which nothing can seem to inspect. Super.

```
Redmine metadata:
Updated on: 2011/04/28 06:51:07 +0000
Start date: 2011/04/22
```

---

**Comment by [Zhorken](http://github.com/zhorken) from 2011/04/27 17:15:34 +0000**

Unfortunately it’s also the latter that comes at a decent resolution. :(

---

**Comment by [Eevee](http://github.com/eevee) from 2011/04/28 06:51:07 +0000**

For, uh, reference: [http://archives.bulbagarden.net/wiki/Category:Pok%C3%A9mon_Dream_World_artwork](http://archives.bulbagarden.net/wiki/Category:Pokémon_Dream_World_artwork)

**Comment by Naramsim** [comment]
Where can we find dreamworld sprites for pokemon ids higer that 646?

**Comment by magical** [comment]
Try the [global-link](http://git.veekun.com/pokedex-media.git/tree/HEAD:/pokemon/global-link) directory. Dream world art does not exist for Gen VI pokemon.
